### ISSUE TITLE
Fix absolute path in FormatNearlyNexus

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#71]

**Comment by jmp1985** [comment]
Looks like this was fixed by @phyy-nx

**Comment by phyy-nx** [comment]
This isn't working yet.  dxtbx.print_header and dials.image_viewer work fine, but when I was trying to add legacy support for distl.signal_strength, I discovered something still isn't right with these links.  Try this patch to see for your self:

Index: FormatHDFEigerNearlyNexus.py
===================================================================
--- FormatHDFEigerNearlyNexus.py	(revision 23762)
+++ FormatHDFEigerNearlyNexus.py	(working copy)
@@ -241,6 +241,9 @@
       del handle['entry/data'][name]
       handle['entry/data'][name] = h5py.ExternalLink(handle_orig['entry/data'][name].file.filename, 'entry/data/data')

+    # Test the re-linking worked
+    assert handle_orig['entry/data'][name].shape == handle['entry/data'][name].shape
+
 class FormatEigerNearlyNexus(FormatHDF5):

   def __init__(self, image_file):

**Comment by jmp1985** [comment]
Changed to use an in-memory file rather than a physical file
